# Generated by Django 3.1.6 on 2021-02-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("item_name", models.CharField(max_length=30, unique=True)),
                (
                    "item_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("is_member", models.BooleanField(default=False)),
                ("current_price", models.IntegerField(default=0)),
            ],
        ),
    ]
