# Generated by Django 3.1.6 on 2021-02-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GE", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="current_price",
        ),
        migrations.RemoveField(
            model_name="item",
            name="is_member",
        ),
    ]
