# Generated by Django 3.1.7 on 2021-02-26 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GE", "0003_auto_20210225_2142"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemPrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DateField(auto_now=True, verbose_name="Price date")),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="GE.item"
                    ),
                ),
            ],
        ),
    ]
