# Generated by Django 3.1.6 on 2021-03-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GE', '0005_auto_20210226_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvalue',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
