# Generated by Django 3.1.6 on 2021-03-01 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GE', '0006_auto_20210301_1210'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemvalue',
            unique_together={('item_id', 'date')},
        ),
    ]
